name: CI - Develop Branch

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy-dev:
    name: Build & Deploy to Development
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/ljt-project-time-tracker
          tags: |
            type=raw,value=dev-${{ github.run_number }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/ProjectTimeTracker.WebAPI/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}